### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by irynka18bz** [irynka18bz/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ira18bz** [comment]
_I am looking for a Quality Assurance Engineer position to apply my skills in software testing. I am really eager to learn new technologies and acquire new skills._

**Comment by irynka18bz** [comment]
**Resume** 
_I am looking for a Quality Assurance Engineer position to apply my skills in software testing. I am really eager to learn new technologies and acquire new skills._
