### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by irynka18bz** [irynka18bz/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by ira18bz** [comment]
**IRYNA SAVCHUK**

- Location: Lviv
- Phone: :+380968341203
- Email: 8341203@gmail.com
- Skype: irynka18bz 
- https://www.linkedin.com/in/iryna-savchuk-180a39b6/
