### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by irynka18bz** [irynka18bz/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by ira18bz** [comment]
**Professional Skills**

- Good knowledge of SDLC, Software Testing Life Cycle 
- Good knowledge of types of testing and test design techniques 
- Writing Test Cases and Bug reports (work in Mantis, TestLink, TestRail and Jira) 
- Requirements Analysis 
- Basic knowledge of SQL (MySQL, Oracle)
- Basic knowledge of REST API 
- Basic knowledge of HTML and CSS
- Familiar with JMeter, Postman

**Languages**
English  - Pre-Intermediate
Ukrainian - native
