### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by irynka18bz** [irynka18bz/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ira18bz** [comment]
**Experience**

_09.2020 –¬ 26.01.2021 – Quality Assurance Group, Trainee Test Engineer:_
- Creating Wireframes and User Flow
- Creating Test Cases in TestRail
- Creating Bugs, User Stories and Acceptance criteria in Jira
- Worked with MySQL
- Testing API with Postman
- Performance testing with JMeter
- Teamwork (Defining business goals of the project; creating Mind Maps; writing Functional and Non-Functional Requirements; creating Test Plan, Traceability Matrix, Checklist, Test Cases; testing; writing Bug Reports and Test Summary Report).

_Mar 2020 QATestLab Training Center:_
Testing websites, creating bug reports in Mantis and test cases in Test Link.

_28.05.2019 – 08.11.2019 Ukrainian Railways company, Civil defence specialist_
Сivil defence property accounting, employees training, creating paperwork of the production unit

_26.01.2016 – 27.05.2019 Ukrainian Railways company, Engineer_
Organising inspections of buildings and structures, creating plans for their repair and write-off from the balance sheet of the enterprise; repair control.
 
**Education**
Sept 2020 - Jan 2021 **Quality Assurance Group**, Software Testing course, 
certificate ID 26012021EST39078014
Mar 2020 – **QATestLab Training Center,** online course "The Fundamentals of Software Testing", certificate No 338289
Jun 2019 – Lviv Training Center programming **"NIKOS-LTV"**, сourse "The basics of web development"
2010-2015 – **Dnepropetrovsk National University of Railway Transport named after Academician V.Lazaryan**, Specialist's degree field of study "Railway buildings and construction; railway economy" obtained the qualification of civil engineer.
